### ISSUE TITLE
Add discovery/scrape-time service selection

### ISSUE THREAD

**Issue by SuperQ** [fastly/fastly-exporter#66]
With Prometheus 2.28, there is now a [generic http service discovery](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config).

The exporter can now produce an API output that lists all of the available services so that they can be scraped independently. This improves the performance of ingestion by spreading it out over time and allowing Prometheus to ingest the data over multiple target threads.

On the Prometheus side, you would configure the job like this:

```yaml
scrape_configs:
- job_name: fastly
  metrics_path: /fastly
  http_sd_configs:
  - url: http://fastly-exporter:8080/sd
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: fastly-exporer:8080 
```

The `/service-discovery` endpoint would output json like this:
```json
[
  { 
    "targets": [
      "<Service ID 1>",
      "<Service ID 2>",
      "<Service ID 3>",
      "<Service ID ...>"
    ]
  }
]
```

The `relabel_config` would then produce exporter URLs like `/fastly?service=<Service ID 1>`.
